title: "Desmond's Portfolio"
email: "your-email@example.com"
description: >-
  Showcasing my projects in electronics, robotics, and AI.
baseurl: "/portfolio" # the subpath of your site
url: "https://desmondttm123.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  desmondttm123
